services:
  php-environment:
    container_name: php-apacheExplicittagsSmashOrPass
    build:
      context: ./app
      dockerfile: ./docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8000:80
      - 8090:8080  # Changed from 8080:8080 to 8090:8080 to avoid conflict
    environment:
      - WEBSOCKET_PORT=8080  # Add this environment variable
  db:
    container_name: dbExplicittagsSmashOrPass
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: headDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
    ports:
      - "9906:3306"
    volumes:
      - dbExplicittagsSmashOrPass_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadminExplicittagsSmashOrPass
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80
volumes:
  dbExplicittagsSmashOrPass_data: